import type { TaskContent } from './types';

// Storyboard Task 6. Clinical detail is draft, pending SME validation.
export const CLOSE_TASK: TaskContent = {
  id: 'close',
  dialogue: {
    speaker: 'Priya',
    text: "This one's yours. He asked to be collected, he wants to talk first, and he hasn't been in a chair for ten years. Slow down, use his name, and give him the controls. I'm right here.",
  },
  signOff: {
    speaker: 'Priya',
    text: "Aspirator's had its disinfectant, sheets are signed, and that's a handover I could actually use tomorrow. That's your day.",
  },
  scenes: [
    {
      place: 'reception',
      eyebrow: 'Waiting room',
      title: 'Collect Graham',
      intro: 'Graham Ellis (54) is a new patient. His notes: extremely anxious, no dentist in over ten years, bad experience as a teenager, asked for a nurse to come and get him, wants to talk first. Sam says he has been here 15 minutes and stepped outside once.',
      decisions: [
        {
          id: 'approach',
          kind: 'choice',
          prompt: 'How do you approach Graham?',
          options: [
            { id: 'door', label: 'From the surgery door: "Graham Ellis? New patient exam?"' },
            { id: 'beside', label: 'Sit beside him, quietly: "Graham? I\'m one of the dental nurses. There\'s no rush at all. When you\'re ready, we\'ll go through and just have a chat with Dr Reid first. Nothing happens today that you haven\'t agreed to."' },
            { id: 'brisk', label: 'Standing in front of him: "Come on, it\'s only a check-up."' },
            { id: 'gap', label: 'Sit beside him: "Ten years is a long time! Don\'t worry, we see it all the time."' },
          ],
          correct: 'beside',
          clause: 'Graham approached beside him, by name, with a line that gives him control',
          feedback: {
            speaker: 'Priya',
            right: 'Low voice, his name, and the one thing he needed to hear: that he is in control of what happens.',
            wrong: "He asked to be collected because being called is part of what frightens him. Go to him. Low voice, his name, and the one thing he needs to hear: that he's in control of what happens. And never mention the gap. He knows exactly how long it's been.",
          },
        },
      ],
    },
    {
      place: 'surgery2',
      eyebrow: 'Surgery 2',
      title: "Graham's examination, then close down",
      intro: 'Graham is in the surgery, sitting forward in the chair. Dr Reid waits for you to settle him. The plain-words examination card is on the worktop.',
      decisions: [
        {
          id: 'offers',
          kind: 'checklist',
          prompt: 'Before Dr Reid begins, tick the three things you offer Graham.',
          after: 'approach',
          options: [
            { id: 'upright', label: 'The chair stays upright to start' },
            { id: 'long_time', label: '"It\'s been a long time!"' },
            { id: 'signal', label: 'Agree the hand-up stop signal' },
            { id: 'nothing_to_worry', label: '"You\'ve nothing to worry about"' },
            { id: 'explain', label: 'Explain the exam in plain words: a small mirror, a thin instrument, counting and noting, and any X-rays only with his agreement' },
            { id: 'guess', label: '"You\'ll probably only need a couple of fillings"' },
          ],
          correct: ['upright', 'signal', 'explain'],
          clause: 'Three appropriate things offered before the exam: control and information',
          feedback: {
            speaker: 'Priya',
            right: 'Control and information. That is what calms people.',
            wrong: "Never mention the time away, he's counting it already. You can't promise there's nothing to worry about, and you certainly can't guess what he'll need. You don't know, and he knows you don't. Offer him control and information. That's what calms people.",
          },
        },
        {
          id: 'howbad',
          kind: 'choice',
          prompt: 'Graham says: "I know they\'re a mess. Go on, tell me how bad it is."',
          after: 'offers',
          options: [
            { id: 'not_bad', label: '"Oh, they\'re not that bad."' },
            { id: 'courage', label: '"You\'ve done the hard part, you\'re here. Dr Reid will have a look and talk you through what she sees, and we go at your pace."' },
            { id: 'ten_years', label: '"Well, ten years is a long time."' },
            { id: 'silence', label: 'Say nothing and carry on setting up' },
          ],
          correct: 'courage',
          clause: "Graham's question answered without judgement or false reassurance",
          feedback: {
            speaker: 'Priya',
            right: 'You acknowledged the courage and handed the assessment to the dentist. Exactly that.',
            wrong: "Two traps. You don't know how his teeth are, so don't reassure him about them; that's Dr Reid's to say. And never, ever comment on the gap. Acknowledge the courage and hand the assessment to the dentist.",
          },
          revealsComplication: true,
        },
        {
          id: 'minute',
          kind: 'choice',
          prompt: 'As Dr Reid reaches for the mirror, Graham sits up: "Sorry. I need a minute outside." He stands. What do you do?',
          after: 'howbad',
          options: [
            { id: 'persuade', label: '"You\'re nearly there, let\'s just get it done." Stay between him and the door' },
            { id: 'follow', label: 'Follow him out to talk him back in' },
            { id: 'let_go', label: 'Let him go. Tell him the door is open, nobody minds, and to come back when he is ready. Tell Dr Reid. When he returns, thank him for coming back' },
          ],
          correct: 'let_go',
          clause: 'Graham given his minute, the door left open, Dr Reid told',
          feedback: {
            speaker: 'Priya',
            right: 'He said a minute; you gave him the minute. And "thank you for coming back", not "are you okay now?".',
            wrong: "Let him go. He said a minute, give him the minute. The door's open, and when he comes back you'll say thank you, not 'are you okay now?'.",
          },
        },
        {
          id: 'distress',
          kind: 'choice',
          prompt: 'Graham is back and the exam is under way. His grip tightens on the armrest and his breathing quickens. What do you do?',
          after: 'minute',
          options: [
            { id: 'relax', label: '"Nearly done, just relax."' },
            { id: 'tell', label: 'Tell Dr Reid quietly and suggest a pause, then a calm line to Graham' },
            { id: 'carry_on', label: 'Carry on. Stopping will only make it longer' },
            { id: 'breathe', label: 'Ask him to breathe with you and tell Dr Reid' },
          ],
          correct: ['tell', 'breathe'],
          clause: "Graham's distress during the exam reported to Dr Reid",
          feedback: {
            speaker: 'Priya',
            right: 'You said it, she paused, he breathed. Same rule as Amira this morning, different patient.',
            wrong: "'Just relax' has never relaxed anyone. You're the one watching him. Say it to Dr Reid, she pauses, he breathes. Same rule as Amira this morning, different patient.",
          },
        },
        {
          id: 'note',
          kind: 'choice',
          prompt: 'Dr Reid dictates: "Full charting done. Patient anxious; managed well with two pauses. Options discussed." Which anxiety note do you write?',
          after: 'distress',
          options: [
            { id: 'judgemental', label: '"Very nervous, hadn\'t been in ten years, teeth in a bad way."' },
            { id: 'factual', label: '"Patient anxious. Prefers to be collected by a nurse, to talk before treatment, chair upright to start, hand-up signal agreed. Two pauses during exam, coped well."' },
            { id: 'fine', label: '"Fine."' },
          ],
          correct: 'factual',
          clause: 'The factual, respectful note is on the record',
          feedback: {
            speaker: 'Priya',
            right: 'The next nurse who meets Graham will read that and know exactly what helps him.',
            wrong: "The next nurse who meets Graham will read this. Tell them what helps him: collected, talk first, chair up, signal agreed, two pauses, coped. Not what you think of his teeth. That's not yours to write, and he'd be mortified to read it.",
          },
        },
        {
          id: 'slip',
          kind: 'choice',
          prompt: 'Dr Reid: "Next visit: hygiene appointment and treatment plan discussion, forty minutes, nurse to collect from the waiting room. Recall to be set at the next visit." Fill in the booking slip for Sam.',
          after: 'note',
          options: [
            { id: 'short', label: 'Twenty minutes, check-up. Recall six months' },
            { id: 'complete', label: 'Forty minutes, hygiene and treatment plan discussion. Nurse to collect from the waiting room. Recall to be set next visit' },
            { id: 'label', label: 'Forty minutes, hygiene and treatment plan. Note: difficult patient' },
          ],
          correct: 'complete',
          clause: 'Booking slip complete and passed to Sam',
          feedback: {
            speaker: 'Priya',
            right: 'Same nurse, same way, next time. Sam can book that.',
            wrong: "The slip is Dr Reid's words for Sam: forty minutes, what it's for, and that he's collected. 'Difficult' is a label, not an instruction. And the recall is set next time, not by you.",
          },
        },
        {
          id: 'closedown',
          kind: 'sequence',
          prompt: 'Graham has gone. Close Surgery 2 for the day. Tap the steps in order.',
          context: 'Priya: "Aspirator gets its disinfectant tonight, sheets signed. Same order as this morning."',
          after: 'slip',
          options: [
            { id: 'sheets', label: 'Check the waste bin and sharps container are not overfull, complete and initial the check sheets' },
            { id: 'flush_water', label: 'Flush the aspirator with water, as between patients' },
            { id: 'instruments', label: 'Clear the tray and take the instruments to decontamination' },
            { id: 'off', label: 'Log off the computer and turn off the light' },
            { id: 'flush', label: 'Flush the water lines, and flush the aspirator with disinfectant solution' },
            { id: 'wipe', label: 'Wipe the surfaces in order, chair top to spittoon, then the hard surfaces' },
          ],
          correct: ['instruments', 'wipe', 'flush', 'sheets', 'off'],
          clause: 'Close-down steps in order, with disinfectant through the aspirator',
          feedback: {
            speaker: 'Priya',
            right: 'Water between patients, disinfectant at the end of the session. The aspirator lines have had a full day through them.',
            wrong: "Water between patients, disinfectant at the end of the session; the aspirator lines have had a full day through them. Dirty out first, then clean, then flush, then the sheets, and the lights go off last. Go again.",
          },
        },
        {
          id: 'handover',
          kind: 'checklist',
          prompt: 'Write your handover for the next nurse. Tick everything that goes in it.',
          context: "Tomorrow's list: 09:00 composite filling, adult, Dr Reid. The template asks: what's ready, what's outstanding, what to watch.",
          after: 'closedown',
          options: [
            { id: 'tray', label: "Tomorrow's first patient is a composite filling at 09:00; tray to set up" },
            { id: 'glucagon', label: 'Glucagon replacement: ordered this morning, check it has arrived' },
            { id: 'delivery', label: 'Delivery on the stock room bench, anaesthetic and concentrate still to check in with Priya' },
            { id: 'graham', label: 'Graham Ellis next visit: forty minutes, nurse to collect, talk first, chair upright' },
            { id: 'teeth', label: "Graham's teeth in a bad way" },
            { id: 'fine', label: 'All fine, surgery done' },
          ],
          correct: ['tray', 'glucagon', 'delivery', 'graham'],
          clause: 'Handover names all four outstanding items',
          feedback: {
            speaker: 'Priya',
            right: "What's ready, what's outstanding, what to watch. Whoever opens up tomorrow can act on every line of that.",
            wrong: "A handover is for the person who wasn't here. If they can't act on it, it isn't one. What's ready, what's outstanding, what to watch, and the glucagon from this morning is exactly the kind of thing that gets lost if it isn't written down.",
          },
        },
      ],
    },
  ],
};
