import type { TaskContent } from './types';

// Storyboard Task 4. Clinical detail is draft, pending SME validation.
export const RESET_TASK: TaskContent = {
  id: 'reset',
  dialogue: {
    speaker: 'Priya',
    text: "Patient first, she's still numb and she's still ten. Then the notes while it's fresh. Then dad. Then this room, in order, no matter who's waiting.",
  },
  signOff: {
    speaker: 'Priya',
    text: "Notes done, dad knows what to watch for, room's reset and the sheet says so. That's a full appointment, start to finish. Most people only ever see the middle bit.",
  },
  scenes: [
    {
      place: 'surgery2',
      eyebrow: 'Surgery 2',
      title: 'Notes, aftercare and reset',
      intro: 'Amira is still in the chair with a numb cheek. Dr Reid is talking to her dad and needs the notes finishing with the batch numbers. Sam has messaged: the 09:40 check-up has arrived.',
      decisions: [
        {
          id: 'care',
          kind: 'sequence',
          prompt: 'Look after Amira as the treatment ends. Tap the steps in order.',
          options: [
            { id: 'glasses', label: 'Glasses off' },
            { id: 'sit', label: 'Help her sit up slowly, and tell her she used the signal exactly right' },
            { id: 'rinse', label: 'Mouthwash and a tissue' },
            { id: 'bib', label: 'Bib off' },
            { id: 'mirror', label: 'Offer her the mirror, if she wants to look' },
          ],
          correct: ['rinse', 'mirror', 'glasses', 'bib', 'sit'],
          clause: "Amira's end-of-treatment care completed in order",
          feedback: {
            speaker: 'Priya',
            right: 'Rinse, mirror, glasses, bib, then up slowly. And you praised the thing she actually did well, not "see, that wasn\'t so bad".',
            wrong: "She's had a mouthful of water and filling dust, and she's been lying flat for half an hour. Deal with the mouth before anything comes off, and sitting up is the slow bit at the end. Go again.",
          },
        },
        {
          id: 'batch',
          kind: 'checklist',
          prompt: 'Dr Reid dictates: "Record the batches." Three packages are on the side. Tick the three numbers that go in the batch fields.',
          context: 'Anaesthetic box: REF 22-0913. LOT 4471B. EXP 03/2027. Composite syringe: REF CP-A2. LOT C0882. Bonding agent bottle: LOT B5510. EXP 11/2026.',
          options: [
            { id: 'la_ref', label: 'Anaesthetic: REF 22-0913' },
            { id: 'la_lot', label: 'Anaesthetic: LOT 4471B' },
            { id: 'la_exp', label: 'Anaesthetic: EXP 03/2027' },
            { id: 'comp_ref', label: 'Composite: REF CP-A2' },
            { id: 'comp_lot', label: 'Composite: LOT C0882' },
            { id: 'bond_lot', label: 'Bonding agent: LOT B5510' },
            { id: 'bond_exp', label: 'Bonding agent: EXP 11/2026' },
          ],
          correct: ['la_lot', 'comp_lot', 'bond_lot'],
          clause: 'Batch numbers for the anaesthetic, composite and bonding agent recorded from the packaging, not the product code or expiry',
          feedback: {
            speaker: 'Priya',
            right: 'Three lot numbers, one per package. If any of those is ever recalled, that is the number the manufacturer asks for.',
            wrong: "Batch or lot, that's the one that tells us which production run this came from. If there's ever a recall, that's the number the manufacturer asks for. Expiry goes in its own field; the product code isn't ours to record.",
          },
        },
        {
          id: 'dictation',
          kind: 'checklist',
          prompt: 'Tick everything from Dr Reid\'s dictation that goes into the notes.',
          context: 'Dr Reid: "Composite restoration completed, lower left back tooth. Local anaesthetic given, record the batch. Patient tolerated well; hand signal used once, water at the back. Aftercare to dad. Recall six months."',
          after: 'batch',
          options: [
            { id: 'restoration', label: 'Composite restoration completed, lower left back tooth' },
            { id: 'la', label: 'Local anaesthetic given, with the batch number' },
            { id: 'signal', label: 'Tolerated well; hand signal used once, water at the back' },
            { id: 'aftercare', label: 'Aftercare given to dad' },
            { id: 'recall6', label: 'Recall six months' },
            { id: 'recall2', label: 'Recall two weeks to check the filling' },
            { id: 'opinion', label: 'Nurse\'s view: went fine, no follow-up needed' },
          ],
          correct: ['restoration', 'la', 'signal', 'aftercare', 'recall6'],
          clause: 'Notes carry the dictation points and a six-month recall',
          feedback: {
            speaker: 'Priya',
            right: "That's the record. What Dr Reid said, in her words, and the recall she decided.",
            wrong: 'The notes are what Dr Reid dictated, nothing added and nothing left out. The recall interval is her decision; you record it, you don\'t change it or add your own view.',
          },
        },
        {
          id: 'aftercare',
          kind: 'checklist',
          prompt: 'Go through the aftercare with Karim. Tick the three points you tell him.',
          context: 'The aftercare card for children\'s fillings is on the wall by the door.',
          options: [
            { id: 'eat_now', label: 'She can eat straight away' },
            { id: 'numb', label: 'No eating or hot drinks until the feeling comes back' },
            { id: 'brush', label: 'Don\'t brush that side for a week' },
            { id: 'bite', label: 'Watch that she doesn\'t bite or chew her numb lip or cheek' },
            { id: 'two_weeks', label: 'Come back in two weeks for a check' },
            { id: 'high', label: 'If the filling feels high when she bites, ring us' },
          ],
          correct: ['numb', 'bite', 'high'],
          clause: 'The three approved aftercare points given to dad',
          feedback: {
            speaker: 'Priya',
            right: "Those three, in plain words. If dad asks anything that isn't on the card, 'ask Dr Reid' is the right answer.",
            wrong: "Two of those aren't true and one's a booking Dr Reid hasn't asked for. Aftercare is only ever what the dentist has said and what's on the card. If dad asks something not on it, 'ask Dr Reid' is the right answer.",
          },
        },
        {
          id: 'sharps',
          kind: 'choice',
          prompt: 'Back in the surgery. The tray has the used instruments, but you cannot see the needle or the matrix band. What do you do?',
          after: 'recall',
          options: [
            { id: 'search', label: 'Search the tray and the bib for the needle so you can put it in the sharps box' },
            { id: 'box', label: 'Assume they are among the instruments and put everything in the transport box' },
            { id: 'reid', label: 'Nothing. Dr Reid put them straight into the sharps container. You never handle a used needle' },
          ],
          correct: 'reid',
          clause: 'Sharps left where Dr Reid put them, never handled',
          feedback: {
            speaker: 'Priya',
            right: "Needle and matrix band went straight from Dr Reid's hand into the sharps box. That's hers, every time.",
            wrong: "Needle and matrix band went straight from Dr Reid's hand into the sharps box, that's hers, every time. You never handle a used needle, and you never go looking for one.",
          },
          revealsComplication: true,
        },
        {
          id: 'sam',
          kind: 'choice',
          prompt: 'A message from Sam: "09:40 has been waiting 10 mins. How long?" What do you reply?',
          after: 'sharps',
          options: [
            { id: 'honest', label: '"Five minutes. Resetting now."' },
            { id: 'quick', label: '"Two minutes." Then skip the flush to make it true' },
            { id: 'ignore', label: 'Don\'t reply. Every second counts' },
          ],
          correct: 'honest',
          clause: 'Sam told how long, honestly, with no step skipped to make it true',
          feedback: {
            speaker: 'Priya',
            right: "Good. She's got a patient asking her, and now she can answer him.",
            wrong: "Tell Sam how long, honestly. She's got a patient asking her. And nobody in this practice will ever ask you to skip an infection control step to save time. If they did, you'd say no and tell me.",
          },
        },
        {
          id: 'reset',
          kind: 'sequence',
          prompt: 'Reset Surgery 2 for the 09:40. Tap the ten steps in order.',
          context: 'Priya: "Top to bottom, dirty to clean. Same order as this morning, it never changes."',
          after: 'sam',
          options: [
            { id: 'wipe', label: 'Wipe surfaces from the top of the chair to the spittoon, then dirty zone to clean zone, and allow contact time' },
            { id: 'ppe', label: 'PPE on: gloves, apron, visor and mask' },
            { id: 'box', label: 'Clean gloves on, wipe every outside surface of the transport box' },
            { id: 'flush', label: 'Flush the water lines and handpiece tubing for 20 to 30 seconds' },
            { id: 'instruments', label: 'Used instruments into the rigid, closed transport box' },
            { id: 'doff', label: 'PPE off into clinical waste, wash or sanitise hands' },
            { id: 'tray', label: 'New tray for the 09:40 and complete the surgery check sheet' },
            { id: 'waste', label: 'Single-use items into clinical waste' },
            { id: 'aspirator', label: 'Flush the aspirator with water' },
            { id: 'gloves_off', label: 'Contaminated gloves off, into clinical waste' },
          ],
          correct: ['ppe', 'instruments', 'waste', 'gloves_off', 'box', 'doff', 'wipe', 'flush', 'aspirator', 'tray'],
          clause: 'Surgery 2 reset in order, no step skipped, check sheet completed',
          feedback: {
            speaker: 'Priya',
            right: 'Dirty out first, box wiped with clean gloves before it leaves, surfaces, lines, aspirator, then the tray and the sheet. The 09:40 waited thirty seconds longer and got a safe room.',
            wrong: "Gloves off before you touch the outside of that box, otherwise the box is as dirty as what's in it. Dirty things leave first, then you clean, then you flush, and the tray and the sheet come last. Go again.",
          },
        },
      ],
    },
    {
      place: 'reception',
      eyebrow: 'Reception',
      title: 'Hand over to Sam',
      intro: 'You walk Amira and her dad out. Sam needs the recall note for the front desk.',
      decisions: [
        {
          id: 'recall',
          kind: 'choice',
          prompt: 'Fill in the recall slip for Sam.',
          after: 'aftercare',
          options: [
            { id: 'two_weeks', label: 'Two weeks, check the filling. Note: first filling' },
            { id: 'six_months', label: 'Six months, check-up. Note: nervous, went well with the hand signal' },
            { id: 'difficult', label: 'Six months, check-up. Note: difficult child, allow extra time' },
          ],
          correct: 'six_months',
          clause: 'Recall note handed to reception with the interval Dr Reid set',
          feedback: {
            speaker: 'Priya',
            right: "Six months, as Dr Reid said, and the note tells whoever sees her next what actually worked.",
            wrong: "The interval is Dr Reid's: six months. And the note is for the next nurse who meets her. 'Nervous, went well with the hand signal' tells them what to do. Anything else is either wrong or unkind.",
          },
        },
      ],
    },
  ],
};
