import type { TaskContent } from './types';

// Storyboard Task 1. Clinical detail is draft, pending SME validation.
export const SETUP_TASK: TaskContent = {
  id: 'setup',
  dialogue: {
    speaker: 'Priya',
    text: "Before anyone sits in that chair, this room has to be clean, working and stocked, and the emergency kit checked. I'll talk you through it once. Then it's yours, and if you're not sure about anything, ask.",
  },
  signOff: {
    speaker: 'Priya',
    text: "Sheets initialled, tray matches the card, and you caught that date. That's a proper set-up. Dr Reid's in at ten to nine.",
  },
  scenes: [
    {
      place: 'surgery2',
      eyebrow: 'Surgery 2',
      title: 'Morning set-up',
      intro: 'The practice has just opened. Surgery 2 is cold and quiet, and both of today\'s check sheets are blank. Work through the set-up with Priya.',
      decisions: [
        {
          id: 'prep',
          kind: 'sequence',
          prompt: 'Get yourself ready to enter the surgery. Tap the steps in the order you would do them.',
          context: 'The 12-step handwashing poster is above the sink, next to the PPE station.',
          options: [
            { id: 'handwash', label: '12-step handwash' },
            { id: 'gloves', label: 'Gloves on' },
            { id: 'uniform', label: 'Uniform and clinical shoes on' },
            { id: 'ppe', label: 'Apron, mask and visor on' },
            { id: 'hair', label: 'Hair tied up and jewellery removed' },
          ],
          correct: ['uniform', 'hair', 'handwash', 'ppe', 'gloves'],
          clause: 'Preparation steps in order: handwash before PPE, gloves last',
          feedback: {
            speaker: 'Priya',
            right: 'Clean hands first, then the PPE over them, gloves last. Nothing touches them on the way on.',
            wrong: 'Think about what touches what. Anything you put on after your hands are clean has to go on without touching them, and gloves are the last thing on, not a substitute for washing. Go again.',
          },
        },
        {
          id: 'wipe',
          kind: 'sequence',
          prompt: 'Wipe the surgery down. Tap the surfaces in the order you would clean them.',
          context: 'Priya: "Top to bottom, cleaner to dirtier. Start with the chair."',
          options: [
            { id: 'spittoon', label: 'Spittoon' },
            { id: 'handles', label: 'Door handles, taps and sink' },
            { id: 'headrest', label: 'Headrest and top of the chair' },
            { id: 'aspirator', label: 'Aspirator hoses and holders' },
            { id: 'surfaces', label: 'Work surfaces and equipment' },
            { id: 'light', label: 'Operating light and handles' },
            { id: 'delivery', label: 'Delivery unit and handpiece holders' },
          ],
          correct: ['headrest', 'light', 'delivery', 'aspirator', 'spittoon', 'surfaces', 'handles'],
          clause: 'Surgery wiped chair first, top to bottom, spittoon last, then hard surfaces',
          feedback: {
            speaker: 'Priya',
            right: "That's it. Chair from the top down, spittoon last, then the hard surfaces. Leave each wipe its contact time before you move on.",
            wrong: "Nearly, but the spittoon's the dirtiest bit of the chair, so it comes last. Top to bottom, cleaner to dirtier, and the surfaces come after the chair. Go again.",
          },
        },
        {
          id: 'flush',
          kind: 'choice',
          prompt: 'How long do you flush the water lines?',
          context: 'Priya: "This is the first flush of the day."',
          options: [
            { id: 'short', label: '20 to 30 seconds' },
            { id: 'two', label: '2 minutes' },
            { id: 'five', label: '5 minutes' },
          ],
          correct: 'two',
          clause: 'Water lines flushed for 2 minutes at the start of the day',
          feedback: {
            speaker: 'Priya',
            right: "Two full minutes first thing. That water has sat in the lines all night.",
            wrong: "Twenty to thirty seconds is between patients. First thing, that water has sat in the lines all night, so it's two full minutes to clear it and stop biofilm building up. Five would just waste the morning.",
          },
        },
        {
          id: 'signoff',
          kind: 'choice',
          prompt: 'The surgery check sheet is done. How do you record it?',
          context: 'The sheet lists surfaces wiped, water lines flushed, aspirator checked, suction running, chair and light working, waste and sharps not overfull.',
          options: [
            { id: 'ticks', label: 'Tick each line' },
            { id: 'initials', label: 'Tick each line and initial it, with the date and time' },
            { id: 'priya', label: 'Tick each line and leave it for Priya to sign' },
          ],
          correct: 'initials',
          clause: 'Surgery check sheet ticked, dated, timed and initialled',
          feedback: {
            speaker: 'Priya',
            right: 'Your initials mean you did the check. If anyone asks in six months, that sheet is the answer.',
            wrong: "A tick on its own tells nobody who did the check. The sheet is only complete when the person who did each line has initialled it, with the date and time. Not me, you did the checks.",
          },
        },
        {
          id: 'kit',
          kind: 'checklist',
          prompt: 'Open the emergency kit. Tick every line on the check sheet that is ready.',
          context: 'Oxygen gauge in the green. AED indicator green. Adrenaline expires next year. Aspirin expires in eight months. Glucagon expired last month.',
          options: [
            { id: 'oxygen', label: 'Oxygen cylinder: level and tested' },
            { id: 'aed', label: 'AED: indicator shows ready' },
            { id: 'adrenaline', label: 'Adrenaline: in date' },
            { id: 'aspirin', label: 'Aspirin: in date' },
            { id: 'glucagon', label: 'Glucagon: in date' },
          ],
          correct: ['oxygen', 'aed', 'adrenaline', 'aspirin'],
          clause: 'Emergency equipment checked and recorded line by line',
          feedback: {
            speaker: 'Priya',
            right: 'Oxygen, AED and two of the three drugs are fine. So what about the third?',
            wrong: 'Have another look at the dates on the drugs box for me. All of them. Only tick a line you have actually checked and found ready.',
          },
          revealsComplication: true,
        },
        {
          id: 'glucagon',
          kind: 'choice',
          prompt: 'The glucagon is out of date. What do you do?',
          after: 'kit',
          options: [
            { id: 'tick', label: 'Tick it anyway. It is only a few weeks over' },
            { id: 'swap', label: 'Fetch a replacement from the stock room and swap it' },
            { id: 'report', label: 'Flag it on the sheet and tell Priya now, before carrying on' },
          ],
          correct: 'report',
          clause: 'Expired glucagon flagged on the sheet and reported to Priya',
          feedback: {
            speaker: 'Priya',
            right: "That's exactly why we check every morning. Nobody's touched that box for weeks, which is the point. Write it on the sheet, and I'll ring the order through. Dr Reid needs to know before nine.",
            wrong: "Checking is only half of it. The other half is what you do with what you find. Tell me now, write it on the sheet, and I'll sort a replacement. It's not yours to swap: emergency drugs are checked in and recorded, not taken off a shelf.",
          },
        },
        {
          id: 'fresh',
          kind: 'choice',
          prompt: 'The room is wiped and checked. Before you open the instrument cupboard to set up the tray, what do you do?',
          context: 'Day list, 09:00: Amira H (10), composite filling. Nervous, first filling, dad attending.',
          options: [
            { id: 'wash_fresh', label: 'Take off the gloves and apron from the wipe-down, 12-step handwash, fresh PPE, then the tray' },
            { id: 'same_gloves', label: 'Keep the same gloves on. They have only touched disinfectant' },
            { id: 'wash_keep', label: 'Wash your hands and put the same gloves back on' },
            { id: 'new_gloves', label: 'Swap the gloves for a new pair, no need to wash in between' },
          ],
          correct: 'wash_fresh',
          clause: 'A fresh handwash and fresh PPE precede the tray set-up',
          feedback: {
            speaker: 'Priya',
            right: 'Dirty job done, dirty PPE off, clean hands, clean PPE, then the sterile stuff. That rhythm runs the whole day.',
            wrong: "Those gloves have just cleaned a surgery. Ask yourself what is about to touch sterile pouches, and whether it should be the same pair. Hands are washed between, not just re-covered.",
          },
        },
        {
          id: 'tray',
          kind: 'checklist',
          prompt: 'Set up the tray for the 09:00 composite filling from the laminated card.',
          after: 'fresh',
          options: [
            { id: 'exam', label: 'Mouth mirror, probe and tweezers (sterile pouch)' },
            { id: 'aspirator', label: 'High-volume aspirator tip and saliva ejector' },
            { id: 'anaesthetic', label: 'Topical gel, with the local anaesthetic left sealed beside the syringe' },
            { id: 'bond', label: 'Etchant and bonding agent' },
            { id: 'composite', label: 'Composite and shade guide' },
            { id: 'matrix', label: 'Matrix band and holder' },
            { id: 'light', label: 'Curing light with barrier sleeve and orange shield' },
            { id: 'finish', label: 'Articulating paper and polishing strips' },
            { id: 'forceps', label: 'Extraction forceps' },
            { id: 'bib', label: 'Patient bib and safety glasses' },
          ],
          correct: ['exam', 'aspirator', 'anaesthetic', 'bond', 'composite', 'matrix', 'light', 'finish', 'bib'],
          clause: 'Tray matches the composite filling card, nothing missing and nothing extra',
          feedback: {
            speaker: 'Priya',
            right: "Tray matches the card. The matrix band is the thin metal strip that wraps round the tooth so the filling sets to the right shape. You'll see Dr Reid use it.",
            wrong: 'Check the tray against the card, item by item. Every line on it has a one-line reason for being there, and anything not on it stays in the cupboard, however important it looks. Forceps are for taking a tooth out. Not today.',
          },
        },
        {
          id: 'pouch',
          kind: 'choice',
          prompt: 'One of the pouches in the cupboard has a broken seal, though the instruments inside look clean. What do you do?',
          after: 'tray',
          options: [
            { id: 'use', label: 'Use it. The instruments look clean' },
            { id: 'tape', label: 'Tape the seal back down and use it' },
            { id: 'aside', label: 'Set it aside for decontamination, take another pouch and tell Priya' },
          ],
          correct: 'aside',
          clause: 'Broken-seal pouch set aside and reported',
          feedback: {
            speaker: 'Priya',
            right: 'Good. It goes back through decontamination, and we know it happened.',
            wrong: "If the seal's broken we can't call it sterile, however clean it looks. Put it to one side so it goes back through decontamination, and take another.",
          },
        },
      ],
    },
  ],
};
