export const ROW_LABELS = {
  order: "Ordered",
  supplierSays: "Supplier says",
  youChecked: "You checked",
  decision: "Decision",
  openNote: "Open the delivery note",
  suppliedFigure: "Supplied figure; no separate supplier document in this activity.",
  weigh: "Weigh it",
  count: "Count them",
  takeTemp: "Take the temperature",
   measuring: "Wait for it to settle",
  inspectFish: "Inspect fish condition",
  findings: "Supplied findings",
  quantity: "Quantity",
  temperature: "Temperature",
  comparisonHeading: "Comparison",
   compareBoth: "Does your quantity match the order and the supplier's claim?",
  matchesBoth: "Matches both",
  differsBoth: "Differs from both",
  differsOrder: "Differs from order",
   differsClaim: "Differs from supplier claim",
  statusHeading: "Status",
  allHere: "All here",
  short: "Short",
  refused: "Refused",
  acceptanceHeading: "Acceptance",
  accept: "Accept",
  refuse: "Refuse",
  acceptChanged: "Quantity changed. Re-confirm acceptance.",
  chickenHint: "Method: Count what came in. Take the temperature. Compare with both figures. Choose to accept or refuse from your findings.",
   openItem: "Open",
   closeItem: "Close",
   noDecision: "Not chosen",
   fishSource: "Compare with the Exmouth Fish delivery note.",
   evidence: "Inspect the goods",
   result: "Result",
   notChecked: "Not checked",
   scaleEmpty: "Nothing on the scales yet. Press ‘Weigh it’ to put the box on.",
   scaleSettled: "Scales settled at",
   readScale: "Read the display, then write the amount in the quantity box.",
   fishReasonHeading: "Which evidence supports accepting the whole fish?",
   fishReasonInspect: "Inspect all four fish findings and take the temperature, then choose your reason.",
   fishReasonEvidence: "The four condition findings and the temperature support accepting the fish.",
   fishReasonQuantity: "The number of fish matches the order, so I would accept them.",
   fishReasonClaim: "The supplier says the order is complete, so I would accept the fish.",
   checked: "The checks and decisions for this item match your evidence.",
   review: "Check these entries",
    measuringReason: "Wait for this reading to settle first.",
    fishOpenReason: "The fish findings are open below.",
};
