/** Interface copy for Task 4's three workspaces. Sentence case; kitchen words glossed on first use. */
export const DIETARY_UI = {
  sheet: {
    title: 'Function sheet',
    menuTitle: "Tonight's menu",
    standardPlate: 'Standard plate for every guest unless the sheet says otherwise: Tart, beef, frangipane.',
    alternatives: 'Alternatives already on the cards: Wellington (vegetarian main) and poached pear.',
    existingTitle: 'Requirements already catered for',
    additionsTitle: 'Added since Tuesday',
    additionsLocked: 'Requirement details open once Terence has been through your chart.',
    additionsOpen: 'Requirement details are open here and in the guest decisions workspace.',
    noteGuest: 'Note this guest',
    noted: 'Noted',
    close: 'Back to the pass',
    opener: {
      what: 'Read the function sheet.',
      how: 'Read it through, then select ‘Close function sheet’ to return to the pass.',
      done: 'You know the event, the menu, and who is already catered for.',
    },
  },
  chart: {
    title: 'Allergen chart',
    hotspot: 'Mark the allergen chart',
    hotspotLocked: 'Read the function sheet first.',
    description: 'Compare the five dishes down the side to the fourteen declarable allergens across the top. Mark what the recipe card shows each dish includes, review what Terence has noted, and jot down any additional checks needed.',
    matchesSupplied: 'Matches the recipe cards',
    recipeEvidence: 'Recipe card',
    ingredients: 'Ingredients',
    notePrefix: 'Card note',
    reviewConfirmation: 'I have checked this row against the card for all fourteen columns, marked what is present, and noted anything I still need to check.',
    terenceReviewConfirmation: 'Checked Terence’s row against the card for all fourteen columns.',
    filledByTerence: 'Filled by Terence',
    correctedByYou: 'Corrected by you',
    openQuestionsLabel: 'Check needed (optional)',
    openQuestionsPlaceholder: 'Anything the card does not tell you, for Terence',
    openQuestionHint: 'A question stays a question. It never becomes a mark on the chart.',
    allergensPresent: 'Allergens in this dish',
    allergensHint: 'Tick a column only when the card shows an ingredient that belongs in it.',
    nextDish: 'Next dish',
    previousDish: 'Previous dish',
    legendTitle: 'Row status',
    legend: {
      'not-started': 'Not started',
      'in-progress': 'In progress',
      reviewed: 'Reviewed',
      'reviewed-question': 'Reviewed, question open',
      flagged: 'Needs another look',
    },
    cellLegend: 'In a reviewed row, an empty cell reads as "checked, not present".',
    referenceTitle: 'What counts as what?',
    referenceHint: 'This is a general reference sheet, not an answer key. Pick a category for a simple description.',
    hintButton: 'Ask Terence for a pointer',
    hintCount: (n: number) => (n === 1 ? '1 pointer so far' : `${n} pointers so far`),
    rowsRemaining: (n: number) => (n === 1 ? '1 row still to review' : `${n} rows still to review`),
    reviewedAll: 'All five rows reviewed',
    tableCaption: 'Allergen chart: Dishes by the fourteen declarable allergens',
    dishColumn: 'Dish',
    statusColumn: 'Status',
    selectedRow: 'Selected row',
    opensRecipeCard: 'Recipe card',
    reviewLocked: 'Mark every row as reviewed before you check your work.',
    progressNoun: 'rows confirmed',
    revisitProgressNoun: 'flagged rows fixed',
    opener: {
      what: 'Check Terence’s three rows. Fill the two dessert rows.',
      how: 'Read each card. Correct any marks, fill both desserts, then confirm every row. Ask Terence to review.',
      done: 'All five rows are confirmed and Terence has reviewed the chart.',
    },
    revisitOpener: {
      what: 'Revisit each row Terence flagged.',
      how: 'Read the card beside each flagged row, correct the marks, confirm the row, then ask Terence again.',
      done: 'Every flagged row is fixed and Terence has reviewed the chart again.',
    },
  },
  guests: {
    title: 'Guest decisions',
    hotspot: 'Decide the guests’ dishes',
    hotspotLocked: 'Check the chart first.',
    subtitle: 'Mains and desserts for the two additions.',
    decisionsMade: 'Both courses checked',
    needsReview: 'To check',
    tablePrefix: 'Table',
    requirementPrefix: 'Function sheet says:',
    scopeNotice: 'You are proposing mains and desserts against the chart, not approving a whole meal.',
    holdNotice: 'Every proposal stays on hold for Terence’s preparation and service checks. Nothing here confirms that a dish is safe.',
    priyaNotice: 'Tree nuts and peanuts are separate columns on your chart. Check both; one allergy does not tell you about the other.',
    tomStarterTitle: 'Starter: Outside this decision',
    plannedDish: 'Planned dish',
    stepFlag: '1. What does your chart say?',
    stepEvidence: '2. Evidence you used',
    stepDecision: '3. Your decision',
    stepReason: '4. Why, in a line the evening team can read',
    proposedDish: 'Replacement dish',
    reasonPlaceholder: 'Keep it short and factual: What the sheet says, what the card shows.',
    evidenceHint: 'Tick what you actually looked at: The sheet, your chart row, ingredients on the card.',
    chartRow: (dish: string) => `Your chart row for the ${dish}`,
    noMarks: 'nothing marked',
    openRecipe: 'Open recipe card',
    hideRecipe: 'Hide recipe card',
    reviewChart: 'Back to the chart',
    nextGuest: 'Next guest',
    checked: 'Checked with Terence',
    incompleteNotice: 'Each main and dessert needs: What the chart says, evidence, a decision, and a reason, checked with Terence.',
    selectPlaceholder: 'Choose a dish from the menu',
    returnsToChart: 'The chart stays open; come back to this guest with the button below.',
    selectGuest: 'Choose this guest',
    checkLocked: 'Tick the evidence and write a reason before you check your work.',
    boardLocked: 'Check every main and dessert before you write the board.',
    progressNoun: 'courses checked',
    opener: {
      what: "Decide each added guest's main and dessert from your chart.",
      how: 'Choose a guest, say what the chart shows for each course, tick the evidence, keep, swap, or ask, give a reason, then check the course with Terence.',
      done: 'Every course for every guest has been checked with Terence.',
    },
  },
  board: {
    title: 'Evening board',
    hotspot: 'Write the evening board',
    hotspotLocked: 'Check every guest decision first.',
    subtitle: 'Every actual change, with the guest, table, original, and replacement, and why. The evening team read this before anything else at three.',
    back: 'Back to guests',
    posted: 'Posted',
    postAndSignOff: 'Post to the board',
    changesTitle: 'Changes to tonight’s plates',
    noChanges: 'No changes recorded yet. A guest whose courses you kept does not go on the board.',
    original: 'Original',
    replacement: 'Replacement',
    reasonLabel: 'Dietary reason',
    reasonPlaceholder: 'From your decision; edit it if the evening team need it plainer.',
    useMyReason: 'Use my reason',
    prepStatusLabel: 'Preparation status',
    prepPending: 'Preparation check pending: Ask Terence before service',
    prepNotRequired: 'No allergy on this change; no preparation check needed.',
    keptTitle: 'Kept as planned (not on the board)',
    forTerenceTitle: 'Open items for Terence',
    openQuestionPrefix: 'Check needed:',
    holdCheckboxLabel: 'I understand this board is a held instruction, not permission to serve. Terence checks preparation before service.',
    postedNotice: 'Posted. The preparation check stays pending; finishing this job does not clear anything for service.',
    boardPreviewTitle: 'As the evening team will read it',
    missingReason: 'Write the reason for this change.',
    postLocked: 'Write every change and acknowledge the preparation hold before posting the board.',
    progressNoun: 'changes written',
    opener: {
      what: 'Put every change on the evening board.',
      how: 'For each change, write the guest, table, original dish, replacement, and reason, then post the board.',
      done: 'The board is posted and the preparation check is pending with Terence.',
    },
  },
};
