/** Every label the student reads at the prep bench and blast chiller in task 3. */
export const CHILL_LABELS = {
  // Objects in the room
  brattPan: 'Portion the beef',
  brattPanHint: 'From the bratt pan (the big tilting pan) into GN trays',
  blastChiller: 'Open the blast chiller',
  blastChillerHint: 'The cabinet that takes hot food down fast',
  record: 'Fill in the chill record',
  recordHint: 'On the clipboard by the chiller',
  backToRoom: 'Room overview',

  // Portioning at the bench
  benchTitle: 'Bratt pan and GN trays',
  pan: 'The bratt pan',
  left: 'left to pan',
  tray: (n: number) => `Tray ${n}`,
  sheetDepth: 'Sheet says 50 mm',
  portionProgress: (moved: number, total: number) => `${moved.toFixed(2)} of ${total.toFixed(1)} kg moved from the pan`,
  trayCapacity: (kg: number, max: number) => `${kg.toFixed(2)} of ${max.toFixed(1)} kg in this tray`,
  trayNeedsMore: (mm: number) => `${mm} mm deep. The prep sheet asks for 50 mm before you ask for another tray.`,
  trayAtDepth: (mm: number) => `${mm} mm deep. This tray has reached the depth on the prep sheet.`,
  trayFull: 'This tray is at its 4 kg limit. Choose another tray.',
  addBeef: 'Add beef',
  addBeefHint: 'Hold to pour steadily, or use the 0.5 kg buttons.',
  returnBeefHint: 'Add beef to this tray first.',
  askForTray: 'Ask Terence for another tray',
  askForTrayHint: 'Fill every tray to the depth on the prep sheet first.',
  panEmpty: 'The pan is empty: all of your half is in the trays',
  toTheChiller: 'Take the trays to the chiller',
  portionOpener: {
    what: 'Portion your half of the pan into GN trays to the depth on the prep sheet.',
    how: 'Tap a tray to choose it, then press and hold Add beef to pour, or use the 0.5 kg buttons.',
    done: 'The pan is empty and every tray is at the depth on the sheet.',
    noun: 'trays at depth',
  },

  // The blast chiller
  chillerTitle: 'Blast chiller',
  cabinet: 'The blast chiller',
  trolley: 'Trays waiting on the trolley',
  trolleyZone: 'Back on the trolley',
  shelf: (n: number) => `Shelf ${n}`,
  shelfZone: (n: number) => `Shelf ${n} of the blast chiller`,
  shelfChoice: (n: number) => `Shelf for tray ${n}`,
  chooseShelf: 'Choose shelf',
  putOnShelf: 'Put on shelf',
  emptyShelf: 'Empty shelf',
  putHere: (carrying: string) => `Put ${carrying.toLowerCase()} here`,
  returnToTrolley: (n: number) => `Return tray ${n} to the trolley`,
  loadStatus: (loaded: number, total: number) => `${loaded} of ${total} trays in the chiller`,
  spacingReady: 'Every tray is loaded with an empty shelf between each one.',
  spacingNeeded: 'The trays are loaded, but at least two are on neighbouring shelves.',
  trayLoaded: (n: number, kg: number) => `Tray ${n}, ${kg.toFixed(1)} kg, in the chiller`,
  trayOnTrolley: (n: number, kg: number) => `Tray ${n}, ${kg.toFixed(1)} kg, on the trolley`,
  touching: 'Touching',
  trolleyEmpty: 'Every tray is in the chiller',
  probe: 'The temperature probe',
  probeHint: 'Drag it into the food',
  probeAlternative: 'Choose a tray, then choose where the probe goes.',
  placeProbeIn: (n: number) => `Place probe in tray ${n}`,
  putProbeHere: 'Put the probe here',
  measureHere: 'Measure here',
  sectionTitle: (n: number) => `Tray ${n}, cut through`,
  sectionQuestion: 'Where in the food does the probe go?',
  sectionZones: {
    surface: 'Just under the surface',
    centre: 'The middle of the beef',
    metal: 'Against the metal',
  },
  leaveItOut: 'Leave it out',
  ruler: 'The ruler',
  rulerHint: 'Drag it to a tray to measure the depth',
  measureFullest: (n: number) => `Measure tray ${n}`,
  rulerZone: (n: number) => `Measure tray ${n}`,
  depthMeasured: (mm: number) => `${mm} mm deep`,
  marcusTrays: "Terence's trays",

  // The panel
  coreTemp: 'Core temperature',
  probeOut: 'Probe not in the food',
  doorOpen: 'Door open',
  cycleRunning: 'Cycle running',
  elapsed: (m: number) => `${m} min in`,
  start: 'Start the chiller',
  startHint: {
    trays: 'Every tray needs to be on a shelf first.',
    space: 'Leave an empty shelf between the trays.',
    probe: 'Put the probe in the food first.',
  },
  saveReadingHint: 'Type the thermometer reading first.',
  holdToRead: 'Hold to take the temperature',
  readAt: (m: number) => `Reading at ${m} minutes`,
  wait: 'Leave it 30 minutes',
  waitHint: (m: number) => `Write the ${m}-minute reading on the chill record first.`,
  waiting: 'Coming back in a bit',
  finished: 'Two hours: the cycle is finished',
  noteIt: 'Write it in your notebook',
  noted: 'In your notebook',
  yourReading: 'What does it say?',
  saveReading: 'Save reading',
  readingHelp: 'Write the number here. It goes straight onto the chill record.',
  settledReading: (value: number) => `The thermometer has settled at ${value.toFixed(1)}°C.`,
  readingSaved: (m: number) => `${m}-minute reading saved to the chill record`,
  readingMismatch: 'That does not match the thermometer. Check the number and try again.',
  comparisonNotice: 'Recorded comparison: 56 mm and 48 mm trays. These example temperatures are not calculated from your practice tray portions.',
  limitsTitle: 'Kitchen limits for this exercise',
  limits: (hold: number, service: number) => `Holding line: ${hold}°C or below. A batch above ${service}°C at ninety minutes does not go to service.`,
  reviewAndSign: 'Review and sign the chill record',
  choiceRight: 'This matches the recorded case. Keep the comparison in the chiller and take the 120-minute reading.',
  choiceWrong: "That doesn't fit this recorded case. Read Terence's response, then choose again.",

  // The chill record
  recordTitle: 'Blast chill record',
  recordBatch: 'Batch: braised beef shin for one hundred',
  columns: { elapsed: 'Elapsed', time: 'Time', yours: 'Example deeper tray (56mm)', marcus: "Terence's tray (48mm)", own: 'Your measured tray' },
  min: 'min',
  useMyNote: 'Use my note',
  depthLine: (own: number, example: number, marcus: number) => `Your measured depth: ${own} mm. Comparison examples: deep tray ${example} mm vs Terence's ${marcus} mm`,
  savedNote: (value: string) => `Your notebook says ${value}. Type the reading into the record.`,
  checkedBy: 'Checked by',
  signHere: 'Sign here',
  signHint: 'Write the 120-minute reading first.',
  readingLockedHint: (m: number) => `Take the ${m}-minute reading first.`,
  execChef: 'Exec chef',
  elenaSigns: 'Terence signs at the end of the day',
  navHint: {
    chiller: 'Portion the beef first.',
    record: 'Start the chiller first.',
  },

  opener: {
    load: {
      what: 'Load the trays into the blast chiller.',
      how: 'Drag each tray from the trolley onto a shelf, or tap a tray and then tap a shelf.',
      done: 'Every tray is on its own shelf with an empty shelf between.',
      noun: 'trays loaded',
    },
    probe: {
      what: 'Put the temperature probe into the food.',
      how: 'Drag the probe onto a tray, or press its Place probe in tray button, then choose where the tip goes.',
      done: 'The probe is placed and the cut-through shows where its tip sits.',
    },
    start: {
      what: 'Start the chill cycle.',
      how: 'Press Start on the control panel.',
      done: 'The clock is running.',
    },
    readings: {
      what: 'Take the reading the chill record asks for.',
      how: 'Press and hold the thermometer until the needle stops, read it, type it in the box and save.',
      done: 'The reading is saved and matches what you read.',
      noun: 'readings saved',
    },
    decision: {
      what: 'Decide what to do with the batch.',
      how: 'Read Terence’s question, then tap one answer.',
      done: 'Terence confirms that your decision fits the recorded case.',
    },
    ruler: {
      what: 'Compare the tray depths.',
      how: 'Drag the ruler onto a tray, or tap the ruler and then tap the tray.',
      done: 'Each tray you measure shows its depth.',
    },
    sign: {
      what: 'Sign the chill record.',
      how: 'Open the chill record, check every reading, then write or type your signature.',
      done: 'Your name appears on the checked by line.',
    },
    record: {
      what: 'Read and correct the chill record.',
      how: 'Tap a reading box to type a correction, then review every row.',
      done: 'Every reached reading matches the thermometer and the record is ready to sign.',
    },
  },

  // What to do next, one line at a time
  next: {
    portion: 'Portion your half of the beef into the trays',
    load: 'Put the trays in the blast chiller, a shelf apart',
    probe: 'Put the probe into the middle of the fullest tray',
    start: 'Start the chiller',
    read: (m: number) => `Take the ${m}-minute reading and write it on the chill record`,
    answer: 'Terence is asking what to do',
    measure: 'Measure the depth of the trays with the ruler',
    wait: 'Nothing to do but wait: leave it 30 minutes',
    sign: 'Sign the chill record',
    done: 'All the work is finished',
  },
};
