/** Every label the student reads at the prep bench and blast chiller in task 3. */
export const CHILL_LABELS = {
  // Objects in the room
  brattPan: 'Portion the beef',
  brattPanHint: 'From the bratt pan (the big tilting pan) into GN trays',
  blastChiller: 'Open the blast chiller',
  blastChillerHint: 'The cabinet that takes hot food down fast',
  record: 'Fill in the chill record',
  recordHint: 'On the clipboard by the chiller',
  backToRoom: 'Room overview',

  // Portioning at the bench
  benchTitle: 'Bratt pan and GN trays',
  ladle: 'The ladle',
  ladleHint: 'Hold it over a tray to pour',
  pan: 'The bratt pan',
  left: 'left to pan',
  tray: (n: number) => `Tray ${n}`,
  trayZone: (n: number) => `Tray ${n}: hold the ladle here to pour`,
  sheetDepth: 'Sheet says 50 mm',
  askForTray: 'Ask Marcus for another tray',
  panEmpty: 'The pan is empty: all of your half is in the trays',
  toTheChiller: 'Take the trays to the chiller',

  // The blast chiller
  chillerTitle: 'Blast chiller',
  cabinet: 'The blast chiller',
  trolley: 'Trays waiting on the trolley',
  trolleyZone: 'Back on the trolley',
  shelf: (n: number) => `Shelf ${n}`,
  shelfZone: (n: number) => `Shelf ${n} of the blast chiller`,
  trayLoaded: (n: number, kg: number) => `Tray ${n}, ${kg.toFixed(1)} kg, in the chiller`,
  trayOnTrolley: (n: number, kg: number) => `Tray ${n}, ${kg.toFixed(1)} kg, on the trolley`,
  touching: 'Touching',
  trolleyEmpty: 'Every tray is in the chiller',
  probe: 'The temperature probe',
  probeHint: 'Drag it into the food',
  sectionTitle: (n: number) => `Tray ${n}, cut through`,
  sectionQuestion: 'Where in the food does the probe go?',
  sectionZones: {
    surface: 'Just under the surface',
    centre: 'The middle of the beef',
    metal: 'Against the metal',
  },
  leaveItOut: 'Leave it out',
  ruler: 'The ruler',
  rulerHint: 'Drag it to a tray to measure the depth',
  rulerZone: (n: number) => `Measure tray ${n}`,
  depthMeasured: (mm: number) => `${mm} mm deep`,
  marcusTrays: "Marcus's trays",

  // The panel
  coreTemp: 'Core temperature',
  probeOut: 'Probe not in the food',
  doorOpen: 'Door open',
  cycleRunning: 'Cycle running',
  elapsed: (m: number) => `${m} min in`,
  start: 'Start the chiller',
  startHint: {
    trays: 'Every tray needs to be on a shelf first.',
    space: 'Leave an empty shelf between the trays.',
    probe: 'Put the probe in the food first.',
  },
  holdToRead: 'Hold to take the temperature',
  readAt: (m: number) => `Reading at ${m} minutes`,
  wait: 'Leave it 30 minutes',
  waitHint: (m: number) => `Write the ${m}-minute reading on the chill record first.`,
  waiting: 'Coming back in a bit',
  finished: 'Two hours: the cycle is finished',
  noteIt: 'Write it in your notebook',
  noted: 'In your notebook',
  yourReading: 'What does it say?',
  saveReading: 'Save reading',
  readingHelp: 'Write the number here. It goes straight onto the chill record.',
  readingSaved: (m: number) => `${m}-minute reading saved to the chill record`,
  readingMismatch: 'That does not match the thermometer. Check the number and try again.',

  // The chill record
  recordTitle: 'Blast chill record',
  recordBatch: 'Batch: braised beef shin for ninety',
  columns: { elapsed: 'Elapsed', time: 'Time', yours: 'Your tray', marcus: "Marcus's tray" },
  min: 'min',
  useMyNote: 'Use my note',
  depthLine: (yours: number, marcus: number) => `Depth: mine ${yours} mm, Marcus's ${marcus} mm`,
  checkedBy: 'Checked by',
  signHere: 'Sign here',
  signHint: 'Write the 120-minute reading first.',
  execChef: 'Exec chef',
  elenaSigns: 'Elena signs at the end of the day',

  // What to do next, one line at a time
  next: {
    portion: 'Portion your half of the beef into the trays',
    load: 'Put the trays in the blast chiller, a shelf apart',
    probe: 'Put the probe into the middle of the fullest tray',
    start: 'Start the chiller',
    read: (m: number) => `Take the ${m}-minute reading and write it on the chill record`,
    answer: 'Marcus is asking what to do',
    measure: 'Measure the depth of the trays with the ruler',
    wait: 'Nothing to do but wait: leave it 30 minutes',
    sign: 'Sign the chill record',
    done: 'All the work is finished',
  },
};
