export const CLOSE_INTERACTION = {
  waste: {
    title: 'Weigh the waste',
    instructions: 'Look in each tub, put it on the scales, then write the reading on its row of the waste sheet. Your notebook is there if you want it.',
    opener: {
      what: 'Weigh each tub of waste and write it on the waste sheet.',
      how: 'Tap a tub, press "Put it on the scales", read the display, then type the weight on that tub’s row.',
      done: 'All three rows are weighed and written.',
      noun: 'tubs weighed',
    },
    chooseTub: 'Choose a tub',
    choose: 'Choose',
    chosen: 'Chosen',
    inTheTub: 'In the tub',
    from: 'From',
    putOnScales: 'Put it on the scales',
    weighAgain: 'Weigh it again',
    scaleLabel: 'Scales',
    settled: 'The scales have settled',
    settling: 'The scales are settling',
    empty: 'Nothing on the scales',
    notWeighed: 'Not weighed yet',
    weighed: 'Weighed',
    waitingForReading: 'Weighed, reading not written yet',
    checkReading: 'Check the reading',
    weightLabel: 'Weight on the waste sheet',
    weightPlaceholder: 'kg',
    writeIt: 'Write the reading you see on the scales.',
    correct: 'This matches the scales.',
    incorrect: 'This does not match the scales. Read them again and check the units.',
    notebook: 'Write it in your notebook',
    notebookDone: 'In your notebook',
    sheetTitle: 'Waste sheet',
    sheetHelp: 'One weight per row, written once. The row goes green when it matches the scales.',
    allWeighed: 'All three rows are weighed and written.',
    nextTub: 'Next tub',
    nextTubReason: 'Write the weight from the scales first.',
    goToHandover: 'Write the handover',
    handoverReason: 'Weigh every tub and write each weight first.',
  },
  evidence: {
    title: 'What you are working from',
    help: 'What you signed, what you were told and what you are asking for. Use it to write the four headings in your own words; nothing here can be changed now.',
    signed: 'From your signed records',
    signedHelp: 'What you wrote and signed today.',
    team: 'From the team',
    teamHelp: 'What people told you or left for you. It is information, not proof anything was done.',
    proposed: 'Proposed follow-up',
    proposedHelp: 'Requests you are passing on. None of them has happened yet.',
    notRecorded: 'not recorded',
    noWasteFollowUp: 'No waste follow-up chosen. That question was optional.',
  },
  handover: {
    title: 'Kitchen handover',
    shift: 'SHIFT: 15:00 - CLOSE',
    instructions: 'Write each heading in your own words. Keep what you saw, what you were told and what you are asking for clearly apart.',
    opener: {
      what: 'Write the handover in your own words.',
      how: 'Fill each of the four headings, group every follow-up by when and who, then press "Hand it over".',
      done: 'The evening team have read it back and you have confirmed.',
      noun: 'headings written',
    },
    placeholder: 'In your own words',
    fieldError: 'Write something under this heading.',
    promptsTitle: 'Check your wording',
    promptsLocked: 'Write your own version first. After you first hand it over, questions to check your wording appear under each heading.',
    prioritiesTitle: 'Group the follow-ups',
    prioritiesHelp: 'Say when each one matters and who does it. Grouping a follow-up does not mark it as done.',
    beforeService: 'Before service',
    later: 'Later follow-up',
    whoLabel: 'Who does it',
    whoPlaceholder: 'Name or role',
    groupingError: 'Choose a timing and name who does it for each follow-up.',
    fieldsError: 'Write something under each heading first.',
    walkThrough: 'Hand it over',
    priorityFeedback: {
      larder2: {
        'before-service': 'This protects tonight’s service: your reading still needs a re-check.',
        later: 'The evening team will question this. Your reading still needs a re-check before service.',
      },
      salmon: {
        'before-service': 'Fine, as long as the evening team know it is tomorrow’s lunch that needs it, not tonight.',
        later: 'Fine for tomorrow’s lunch, as long as someone is named and it is not left open-ended.',
      },
      table3: {
        'before-service': 'This keeps the pear on hold for its preparation and service checks before dessert goes.',
        later: 'The evening team will question this. The pear still needs its checks before it can be served.',
      },
    },
  },
  review: {
    title: 'Review the cooling record with Terence',
    instructions: 'Answer Terence from the recorded comparison. His signature confirms this record review, not service clearance.',
    opener: {
      what: 'Answer Terence’s question about cooling the beef and ask him to sign.',
      how: 'Tap an answer, read Terence’s response, then press "Ask Terence to sign".',
      done: 'The cooling question is answered correctly and Terence has signed.',
    },
    checkedBy: 'Checked by',
    signature: 'Terence — Executive sous chef',
    role: 'Executive sous chef',
    askToSign: 'Ask Terence to sign',
    signReason: 'Answer Terence’s question first.',
  },
} as const;
