export const SCENE_LABELS = {
  goToBackDoor: "Head to the back door",
  backDoorHint: "Where the delivery van is waiting",
  takeDeliveryNote: "Take the delivery note",
  readDeliveryNote: "Read the delivery note",
  deliveryNote: "Delivery note",
  checkOrderSheet: "Check the order sheet",
  orderSheet: "Order sheet",
  deliveryCheckSheet: "Delivery check sheet",
  supplierLine: "Supplier: Devon Fresh / Exmouth Fish",
  trolleys: {
    1: "Trolley 1: fish",
    2: "Trolley 2: chilled",
    3: "Trolley 3: fruit and veg"
  },
  backToTrolley: "Back to the trolley",
  count: "Count them",
  weigh: "Weigh it",
  takeTemperature: "Take the temperature",
  writeInNotebook: "Write it in your notebook",
  inNotebook: "In your notebook",
  useMyNote: "Use my note",
  radioMarcus: "Radio Terence",
  signNote: "Sign the note",
  allChecked: "All checked",
  status: {
    arrived: "All here",
    short: "Short",
    refused: "Refused"
  },
  next: {
    note: "Take the delivery note from the driver",
    boxes: "Check the boxes on the trolleys",
    sheet: "Fill in the order sheet",
    radio: "Prepare your report for Terence",
    sign: "Review the amendment and sign for what you accept",
    done: "All done: open your job card"
  },
  openNextBox: "Open the next box",
  checkEntries: "Check your entries",
  prepareReport: "Prepare your report",
  matchesBoth: "Matches both",
  differsBoth: "Differs from both",
  differsOrder: "Differs from order",
  differsClaim: "Differs from note",
  accept: "Accept",
  refuse: "Refuse",
  amendNote: "Amend the delivery note",
  verifyWithDriver: "Check comparison",
  sendReport: "Send report to Terence",
  workspace: {
    opener: {
      item: {
        what: "Check this item beside its entry.",
        how: "Count or weigh it, take the temperature if chilled, write what arrived, compare the papers, then choose accept or refuse.",
        done: "The row has findings and a decision.",
      },
      comparison: {
        what: "Work out the shortfall and the amount for the supplier note.",
        how: "Choose an item, compare the three amounts, type what is missing, then prepare and check the amendment.",
        done: "The shortfall is checked and the proposed amendment is saved.",
      },
      report: {
        what: "Tell Terence what needs following up.",
        how: "Choose the affected item, service and action, then press Send report.",
        done: "Terence has received a correct report.",
      },
      note: {
        what: "Confirm and sign the supplier note amendment.",
        how: "Choose the fish, confirm the accepted amount, add your initials, review the note, then sign it.",
        done: "The amendment is initialled and the note is signed.",
      },
      review: {
        what: "Resolve every unfinished check.",
        how: "Press an issue to return to its source, finish it, then come back to review.",
        done: "No issues remain and the supplier note is ready to sign.",
      },
    },
    title: "Working order sheet",
    introduction: "Open each item, check it and write your results here. Your entries stay on this sheet.",
    allItems: "All ten items",
    sheet: "Order sheet",
    comparison: "Compare amounts",
    note: "Fish supplier note",
    report: "Report to Terence",
    review: "Review before signing",
    back: "Back to the sheet",
    briefing: "Read the briefing",
    unchecked: "Unchecked",
    unfinished: "Unfinished",
    ready: "Ready to review",
    readyHelp: "Ready to review means you have made your entries, not that they have been checked.",
    reviewHelp: "Check any unfinished work or contradictions before you sign. Open a message to return to its source.",
    reviewClear: "Your checks, report and amendment are ready. Open the fish supplier note to sign.",
    signed: "The note is signed. Use “On to the next job” above to sign off this task.",
    reviewAgain: "Review again",
    openNote: "Open the fish note",
    briefingMentor: "Terence",
    briefingDriver: "Driver",
    support: "Start with smoked haddock for a short guide to the method, or choose any item.",
    inspectionProgress: (counted: number, probed: number, fish: number) =>
      `${counted}/10 quantities checked · ${probed}/6 temperatures taken · ${fish}/4 fish findings inspected`,
    navigationLocked: {
      comparison: "Finish every item check first.",
      report: "Check the comparison first.",
      note: "Send the report to Terence first.",
    },
  },
  comparisonSheet: {
    title: "Compare your amounts",
    instruction: "Choose the item you need to report. Compare your check with the kitchen order and the supplier's claim, then work out what is missing.",
    product: "Item to report",
    choose: "Choose an item",
    ordered: "Kitchen order",
    claimed: "Supplier says",
    observed: "You checked",
    accepted: "You chose to accept",
    blank: "Not entered",
    missing: "Amount missing",
    proposal: "Prepare the fish-note amendment",
    proposalHelp: "Choose the line to change and propose the amount you will sign for. This does not initial or sign the note.",
    fishLine: "Fish-note line to amend",
    chooseFish: "Choose a fish-note line",
    amount: "Proposed amendment",
    useAccepted: "Use my accepted amount",
    useAcceptedReason: "Choose a fish and save its accepted amount first.",
    check: "Check comparison",
    incomplete: "Finish the physical checks and your quantity, temperature, comparison, status and acceptance decisions. Enter your missing amount and proposed note amendment, then check again.",
    serviceContext: "What has come up",
    editHint: "The entries are still yours to correct. No amount has been changed for you.",
    hintTitle: "Help with the comparison",
    hintFind: "Read the order and supplier claim beside your own checked amount.",
    hintMethod: "Subtract what arrived from what was ordered. The missing amount is different from the amount you accept.",
    hintWorked: "Work it through",
    worked: "The order and supplier claim are 12 kg. The scales show 8 kg. That leaves 12 − 8 = 4 kg missing. The 8 kg delivered is suitable to accept, so the signed note should show 8 kg, not the 4 kg missing.",
    goReport: "Prepare the report",
  },
};
