export const DELIVERY_PAPERWORK = {
  note: {
    supplier: 'Exmouth Fish Suppliers',
    number: 'Delivery note #49281',
    account: 'Account: MAR-EXETER',
    date: 'Date: Today',
    description: 'Description',
    quantity: 'Quantity',
    originalClaim: 'Supplier claim',
    affectedFish: 'Choose the fish to amend',
    chooseFish: 'Choose a fish',
    amendedAmount: 'Amount accepted on the amended note',
    amendedAmountHint: 'Write the amount you are accepting, not the amount missing.',
    useAcceptedAmount: 'Use my accepted amount',
    acceptedAmountUnavailable: 'No accepted amount has been saved for this fish.',
    amendmentInitials: 'Initials beside the amendment',
    typeInitials: 'Type your initials',
    initialAmendment: 'Initial amendment',
    initialHint: 'Choose a fish and write the amended amount first.',
    received: 'Received in good condition',
    review: 'Review before signing',
    reviewHeading: 'Check these before signing',
    goToSource: 'Go to this check',
    sign: 'Sign the note',
    signed: 'Signed',
    signatureStale: 'The note changed after you signed it. Review the changes and sign it again.',
  },
  report: {
    product: 'Affected product',
    chooseProduct: 'Choose a product',
    savedShortage: 'Your saved missing amount',
    noSavedShortage: 'Not entered',
    editComparison: 'Check the comparison',
    service: 'Service affected',
    action: 'Action needed',
    serviceOptions: {
      tomorrowLunch: "Tomorrow's lunch",
      tonightLaunch: "Tonight's launch",
      both: 'Both services',
    },
    actionOptions: {
      contactSupplier: 'Contact the supplier',
      changeTonightMenu: "Change tonight's menu",
      noFollowUp: 'No follow-up needed',
    },
    lockedContext: 'Finish the comparison and proposed note amendment to reveal the service information.',
    contextHeading: 'What the job card says',
    previewHeading: 'Message preview',
    previewHint: 'This message is made from the entries you have written.',
    send: 'Send report',
    resend: 'Resend report',
    correctionHeading: 'Terence needs you to check these details',
    sourceLink: 'Check the source',
    terenceReply: 'Terence replies',
    sentHeading: 'Message sent',
    close: 'Close report',
  },
} as const;