/** Interface copy for Task 4's three workspaces. Sentence case; kitchen words glossed on first use. */
export const DIETARY_UI = {
  sheet: {
    title: 'Function sheet',
    menuTitle: "Tonight's menu",
    standardPlate: 'Standard plate for every guest unless the sheet says otherwise: tart, beef, frangipane.',
    alternatives: 'Alternatives already on the cards: Wellington (vegetarian main) and poached pear.',
    existingTitle: 'Requirements already catered for',
    additionsTitle: 'Added since Tuesday',
    additionsLocked: 'Requirement details open once Terence has been through your chart.',
    additionsOpen: 'Requirement details are open here and in the guest decisions workspace.',
    noteGuest: 'Note this guest',
    noted: 'Noted',
    close: 'Back to the pass',
  },
  chart: {
    title: 'Allergen chart',
    description: 'Five dishes down the side, the fourteen declarable allergens across the top. Mark what the recipe card shows, review each row, and note anything you cannot tell from the card.',
    matchesSupplied: 'Matches the recipe cards',
    reviewWithTerence: 'Review with Terence',
    nextDecisions: 'Next: guest decisions',
    recipeEvidence: 'Recipe card',
    ingredients: 'Ingredients',
    notePrefix: 'Card note',
    reviewConfirmation: 'I have checked this row against the card for all fourteen columns, marked what is present and noted anything I still need to check.',
    openQuestionsLabel: 'Check needed (optional)',
    openQuestionsPlaceholder: 'Anything the card does not tell you, for Terence',
    openQuestionHint: 'A question stays a question. It never becomes a mark on the chart.',
    allergensPresent: 'Allergens in this dish',
    allergensHint: 'Tick a column only when the card shows an ingredient that belongs in it.',
    nextDish: 'Next dish',
    previousDish: 'Previous dish',
    legendTitle: 'Row status',
    legend: {
      'not-started': 'Not started',
      'in-progress': 'In progress',
      reviewed: 'Reviewed',
      'reviewed-question': 'Reviewed, question open',
      flagged: 'Needs another look',
    },
    cellLegend: 'In a reviewed row, an empty cell reads as "checked, not present".',
    referenceTitle: 'What counts as what',
    referenceHint: 'General reference, not an answer key. Pick a category for a plain-language description.',
    hintButton: 'Ask Terence for a pointer',
    hintCount: (n: number) => (n === 1 ? '1 pointer so far' : `${n} pointers so far`),
    rowsRemaining: (n: number) => (n === 1 ? '1 row still to review' : `${n} rows still to review`),
    reviewedAll: 'All five rows reviewed',
    tableCaption: 'Allergen chart: dishes by the fourteen declarable allergens',
    dishColumn: 'Dish',
    statusColumn: 'Status',
    selectedRow: 'Selected row',
  },
  guests: {
    title: 'Guest decisions',
    subtitle: 'Mains and desserts for the three additions.',
    decisionsMade: 'Both courses checked',
    needsReview: 'To check',
    tablePrefix: 'Table',
    requirementPrefix: 'Function sheet says:',
    scopeNotice: 'You are proposing mains and desserts against the chart, not approving a whole meal.',
    holdNotice: 'Every proposal stays on hold for Terence’s preparation and service checks. Nothing here confirms a dish as safe.',
    priyaNotice: 'Tree nuts and peanuts are separate columns on your chart. Check both; one allergy does not tell you about the other.',
    tomStarterTitle: 'Starter: outside this decision',
    plannedDish: 'Planned dish',
    stepFlag: '1. What does your chart say?',
    stepEvidence: '2. Evidence you used',
    stepDecision: '3. Your decision',
    stepReason: '4. Why, in a line the evening team can read',
    proposedDish: 'Replacement dish',
    reasonPlaceholder: 'Keep it short and factual: what the sheet says, what the card shows.',
    evidenceHint: 'Tick what you actually looked at: the sheet, your chart row, ingredients on the card.',
    chartRow: (dish: string) => `Your chart row for the ${dish}`,
    noMarks: 'nothing marked',
    openRecipe: 'Open recipe card',
    hideRecipe: 'Hide recipe card',
    reviewChart: 'Back to the chart',
    nextGuest: 'Next guest',
    reviewBoard: 'Go to the evening board',
    checkWithTerence: 'Check this with Terence',
    checked: 'Checked with Terence',
    incompleteNotice: 'Each main and dessert needs: what the chart says, evidence, a decision and a reason, checked with Terence.',
    selectPlaceholder: 'Choose a dish from the menu',
    returnsToChart: 'The chart stays open; come back to this guest with the button below.',
  },
  board: {
    title: 'Evening board',
    subtitle: 'Every actual change, with the guest, table, original and replacement, and why. The evening team read this before anything else at three.',
    back: 'Back to guests',
    posted: 'Posted',
    postAndSignOff: 'Post to the board',
    changesTitle: 'Changes to tonight’s plates',
    noChanges: 'No changes recorded yet. A guest whose courses you kept does not go on the board.',
    original: 'Original',
    replacement: 'Replacement',
    reasonLabel: 'Dietary reason',
    reasonPlaceholder: 'From your decision; edit it if the evening team need it plainer.',
    useMyReason: 'Use my reason',
    prepStatusLabel: 'Preparation status',
    prepPending: 'Preparation check pending: ask Terence before service',
    prepNotRequired: 'No allergy on this change; no preparation check needed.',
    keptTitle: 'Kept as planned (not on the board)',
    forTerenceTitle: 'Open items for Terence',
    openQuestionPrefix: 'Check needed:',
    holdCheckboxLabel: 'I understand this board is a held instruction, not permission to serve. Terence checks preparation before service.',
    postedNotice: 'Posted. The preparation check stays pending; finishing this job does not clear anything for service.',
    boardPreviewTitle: 'As the evening team will read it',
  },
};
