export const DIETARY_UI = {
  chart: {
    title: "Allergen matrix",
    description: "Check all 14 categories for every dish against the supplied ingredients. Mark those present. Do not invent details you aren't given.",
    matchesSupplied: "Matches supplied ingredients",
    reviewWithTerence: "Review with Terence",
    nextDecisions: "Next: Guest decisions",
    recipeEvidence: "Recipe Evidence",
    ingredients: "Ingredients",
    notePrefix: "Note:",
    reviewConfirmation: "I've checked all fourteen categories against these ingredients. I've marked those present and noted anything I need to check.",
    openQuestionsLabel: "Open questions (e.g. supplier details)",
    openQuestionsPlaceholder: "Any unresolved details?",
    allergensPresent: "Allergens Present",
    allergensHint: "Select all that apply based on the ingredients.",
    nextDish: "Next dish"
  },
  guests: {
    title: "Guest list",
    subtitle: "Review the added guests.",
    decisionsMade: "Decisions made",
    needsReview: "Needs review",
    tablePrefix: "Table",
    requirementPrefix: "Requirement:",
    generalNotice: "You are proposing mains and desserts, not approving a whole meal. Tom's fish starter still needs a separate decision.",
    holdNotice: "All proposals remain on hold for Terence's supplier, preparation and service checks.",
    priyaNotice: "The sheet says “nut allergy”. Tree nuts and peanuts are separate categories; ask Terence to confirm the exact requirement rather than assuming one allergy means both.",
    plannedDish: "Planned dish",
    decision: "Decision",
    proposedDish: "Proposed dish",
    reasonCategory: "Reason category",
    yourReason: "Your reason or question",
    reasonPlaceholder: "Explain why keeping, swapping, or asking...",
    selectEvidenceTitle: "Select Evidence",
    selectEvidenceHint: "Select evidence from the recipes below to support your decision.",
    requiredBadge: "Required",
    recipesAndChart: "Recipes & Chart",
    chartMarks: "Your Chart Marks:",
    noMarks: "No categories marked",
    reviewChart: "Review the chart",
    nextGuest: "Next Guest",
    reviewBoard: "Review the evening board",
    incompleteNotice: "Check each main and dessert: dish, decision, reason category, evidence and your explanation.",
    selectPlaceholder: "Select dish...",
    categoryPlaceholder: "Select category..."
  },
  board: {
    title: "Evening board",
    subtitle: "Leave clear instructions for the evening team.",
    back: "Back",
    posted: "Posted to board",
    postAndSignOff: "Post board & sign off",
    boardMessage: "Board message",
    insertDraft: "Insert draft from decisions",
    placeholder: "Guest · Table · Original → Replacement · Dietary reason",
    prepChecksTitle: "Preparation & service checks",
    supplierResponses: "Supplier/Prep responses",
    serviceHoldWarning: "Service hold: You have open preparation questions. The board is a held instruction, not permission to serve.",
    holdCheckboxLabel: "Proposed menu: hold for Terence’s preparation/service check"
  }
};