export const HANDOVER_LABELS = {
  opener: {
    log: {
      what: "Read the night team's notes.",
      how: "Scroll through the log, then press “Let's check the fridges” at the bottom.",
      done: "The fridge round has started.",
    },
    inspection: {
      what: "Check this fridge and write down what you find.",
      how: "Open the fridge, tick the evidence you see, press “Take the temperature”, read the dial, type the reading, then save.",
      done: "The row is saved and you move to the next fridge.",
    },
    board: {
      what: "Check the board reads right.",
      how: "Read each row. Press Recheck on a fridge to look at it again.",
      done: "Every row is saved and nothing needs a second look.",
    },
  },
  startRound: "Let's check the fridges",
  overnightLog: "Overnight log",
  openFridge: "Open the fridge",
  closeFridge: "Close door",
  saveAndClose: "Done, close the door",
  closeAndContinue: "Close and continue",
  closeAndReturn: "Close and return to board",
  holdToRead: "Take the temperature",
  probeValue: "What did it read? (°C)",
  time: "Time",
  initials: "Initials",
  note: "What did you find?",
  noteOptional: "Anything worth noting? (optional)",
  notePlaceholder: "Write what you found and what you did",
  correctiveNotePrompt: "What did you do about it?",
  boardTitle: "Temperature board",
  boardRound: "06:45 ROUND",
  recheck: "Recheck",
  saveBoard: "Sign off board",
  readingError: "Have another look at the probe and write that number.",
  initialsError: "Don't forget your initials.",
  noteError: "Check inside the fridge, then write what you found and what you did.",
  writeInNotebook: "Write it in my notebook",
  inNotebook: "Written in your notebook. Open Notebook at the top to read it.",
  inspectPrompt: "Have a look around",
  inspectHint: "Check the numbered areas, then use the findings in your own note.",
  progress: (saved: number, total: number) => `${saved} of ${total} done`,
  finishCurrentReason: "Save the current fridge before opening another one.",
  takeReadingReason: "Take the temperature first.",
  completeEntryReason: "Take the temperature before saving this row.",
  frozenReason: "This board is signed off and stays as you left it.",
};
