export const HANDOVER_LABELS = {
  startRound: "Let's check the fridges",
  overnightLog: "Overnight log",
  openFridge: "Open door",
  closeFridge: "Close door",
  saveAndClose: "Done — close the door",
  closeAndContinue: "Close and continue",
  closeAndReturn: "Close and return to board",
  holdToRead: "Hold the probe in",
  probeValue: "What did it read? (°C)",
  time: "Time",
  initials: "Initials",
  note: "What did you find?",
  noteOptional: "Anything worth noting? (optional)",
  notePlaceholder: "Write what you found and what you did",
  correctiveNotePrompt: "What did you do about it?",
  boardTitle: "Temperature board",
  boardRound: "06:45 ROUND",
  recheck: "Recheck",
  saveBoard: "Sign off board",
  readingError: "Have another look at the probe and write that number.",
  initialsError: "Don't forget your initials.",
  noteError: "Check inside the fridge, then write what you found and what you did.",
  writeInNotebook: "Keep this in my notebook",
  inspectPrompt: "Have a look around",
  inspectHint: "Select the markers on the fridge to see what you find.",
  progress: (saved: number, total: number) => `${saved} of ${total} done`,
};
