export const DELIVERY_FEEDBACK = {
  missingLine: 'This item is missing from the order sheet.',
  inspectQuantity: 'Inspect and count or weigh this item.',
  quantity: (unit: string) => `Write the quantity you checked in ${unit}.`,
  temperatureInspection: 'Take the temperature of this item.',
  temperatureEntry: 'Write the temperature shown after it settles.',
  comparison: 'Compare your quantity with both amounts on the paperwork.',
  status: 'Choose whether this item is all here, short, or refused.',
  acceptance: 'Decide whether to accept the goods you checked.',
  acceptedAmount: 'Confirm the amount you are accepting.',
  salmonClaimedAsObserved: "That matches the supplier's note. Compare it with your scales.",
  salmonQuantityAndCondition: 'Compare the quantity with the order, then consider the condition separately. Check whether the goods themselves are suitable.',
  creamTemperatureDecision: 'Look at the temperature you wrote. Compare it with the limit on the sheet.',
  context: 'Check the comparison before preparing the report.',
  reportProduct: 'Choose the product with the discrepancy.',
  reportEvidence: 'Finish the salmon inspection and comparison before reporting it.',
  missingAmount: 'Work out and enter the amount missing.',
  missingVersusAccepted: 'The missing amount is not the amount accepted. Compare the order with what arrived.',
  reportService: 'Choose the service affected by the shortage.',
  reportAction: 'Choose the follow-up this shortage needs.',
  reportSend: 'Preview and send a current report to Terence.',
  fish: 'Inspect all four findings on the whole sea bass.',
  fishReason: 'Use the fish findings and your saved temperature to choose the reason for your decision.',
  noteAmount: 'Amend the note to the amount you accepted, not the amount missing.',
  noteInitials: 'Initial the amendment.',
  noteAmountFor: (item: string) => `Amend ${item} to the amount you accepted.`,
  noteInitialsFor: (item: string) => `Initial the ${item} amendment.`,
  noteUnexpectedAmendmentFor: (item: string) => `Your sheet says ${item} matched the supplier's claim. Clear the amendment against it, or change your decision on the sheet.`,
  noteRefusal: 'Record that the cream was refused.',
  noteTemperature: 'Record the cream temperature on the note.',
  signature: 'Sign the supplier note.',
} as const;