export const FRIDGE_INTERACTION_COPY = {
  roundOrientation: 'Fridge round',
  currentAppliance: 'Current',
  checkedAppliance: 'Checked',
  waitingAppliance: 'Waiting',
  chooseAppliance: (name: string) => `Return to ${name}`,
  evidenceHeading: 'What you can check',
  evidenceProgress: (checked: number, total: number) => `${checked} of ${total} findings checked`,
  probeReady: 'The probe has settled. Write the reading on the board yourself.',
  withinLimit: (reading: string, limit: string) => `${reading} °C meets the stated limit: ${limit}.`,
  aboveLimit: (reading: string, limit: string) => `${reading} °C does not meet the stated limit: ${limit}. Use what you find inside to explain the issue and what you did to fix it.`,
  noteProbePrompt: 'Take the temperature before writing the board entry.',
  notebookSaved: 'Reading added to your notebook.',
  rowSaved: (name: string) => `${name} saved. The door is closed.`,
  closedHint: 'Open the door to inspect inside.',
  opening: 'Opening the door',
  skipOpening: 'Inspect now',
  checkHeading: 'Your fridge check',
  checkHint: 'Look inside, take the temperature, then write your reading and any observations here.',
} as const;