export const FRIDGE_INTERACTION_COPY = {
  roundOrientation: 'Fridge round',
  currentAppliance: 'Current',
  checkedAppliance: 'Checked',
  waitingAppliance: 'Waiting',
  chooseAppliance: (name: string) => `Return to ${name}`,
  evidenceHeading: 'What you can check',
  evidenceProgress: (checked: number, total: number) => `${checked} of ${total} findings checked`,
  takeSubtitle: 'Wipe the dial and wait for the needle to settle',
  settling: 'The needle is settling.',
  probeReady: 'The needle has settled. Read the dial and write the temperature on the board yourself.',
  limitReminder: (limit: string) => `This unit should be ${limit}.`,
  noteProbePrompt: 'Take the temperature before writing the board entry.',
  notebookHint: 'Write your reading first, then keep a copy in your notebook.',
  notebookSaved: 'Reading added to your notebook.',
  rowSaved: (name: string) => `${name} saved. The door is closed.`,
  closedHint: 'Open the door to inspect inside.',
  opening: 'Opening the door',
  skipOpening: 'Inspect now',
  checkHeading: 'Your fridge check',
  checkHint: 'Look inside, read the thermometer, then write your reading and any observations here.',
} as const;