export const WELCOME_COPY = {
  title: "A day as a sous chef.",
  subtitle: "Interactive Try Day",
  shortBrief: "Join Marcus in a hotel kitchen preparing for tonight’s wedding. Check the food, make decisions and get the evening team ready.",
  launchButton: "Expand experience",
  launchHint: "Open the briefing, then start your shift.",
  returnButton: "Back to welcome",
  close: "Close",
  briefingTitle: "Before your shift",
  briefing: "You’re the trainee sous chef. Work with Marcus to prepare the kitchen for a wedding of ninety guests.",
  instructions: [
    "Inspect food, take measurements and complete the kitchen records.",
    "Follow the step guide through five tasks. Check your work before signing it off.",
  ],
  controls: "Use a mouse, touch or keyboard. Sound is optional.",
  fullBrief: "Read Marcus’s full briefing",
  shift: "Simulated shift",
  nameLabel: "What should we call you?",
  nameHelp: "Your initials go on the kitchen records you complete.",
  namePlaceholder: "Your name",
  start: "Start simulation",
  welcomeBack: (name: string) => `Welcome back, ${name}`,
  completed: "You’ve finished the shift. Read your close of day again, or start a new shift.",
  resume: (time: string, title: string) => `Continue from ${time}: ${title}.`,
  resumeFallback: "Continue where you left off.",
  continue: "Continue simulation",
  readClose: "Read the close of day",
  reset: "Start again",
  resetWarning: "Start a new shift? This will clear your saved work for the current shift.",
  confirmReset: "Yes, start again",
  cancelReset: "Keep my progress",
};
